binary_name := module_test_vgm_voices
dirs.root := ../../../..
source_dirs := .

libraries.common = analysis \
                   binary binary_compression binary_format_lite \
                   core core_plugins_archives_lite core_plugins_players debug \
                   devices_aym devices_beeper devices_dac devices_fm devices_saa devices_z80 \
                   formats_chiptune formats_packed formats_archived formats_archived_multitrack formats_multitrack \
                   l10n_stub module \
                   parameters \
                   sound strings \
                   tools

libraries.3rdparty = asap atrac9 ffmpeg FLAC gme he ht hvl lazyusf2 lhasa lzma mpg123 ogg openmpt opus mgba sidplayfp snesspc sseqplayer unrar v2m vgm vgmstream vio2sf vorbis xmp z80ex zlib

include $(dirs.root)/makefile.mak
